#version 460 core

// Copyright 2026 m4jr0. All Rights Reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

#ifndef LOCAL_SIZE
#define LOCAL_SIZE 256
#endif  // LOCAL_SIZE

struct DebugAabb {
  vec3 minExtents;
  vec3 maxExtents;
};

layout(local_size_x = LOCAL_SIZE) in;

layout(std430, binding = 25) readonly buffer InDebugAabbsSsbo {
  DebugAabb inDebugAabbs[];
};

layout(std430, binding = 26) buffer OutDebugLineVertexBuffer {
  vec4 outLineVertices[];
};

layout(std140, binding = 50) uniform DebugPushConstants { uint count; }
pushConstants;

const ivec2 cubeEdges[12] =
    ivec2[](ivec2(0, 1), ivec2(1, 2), ivec2(2, 3), ivec2(3, 0), ivec2(4, 5),
            ivec2(5, 6), ivec2(6, 7), ivec2(7, 4), ivec2(0, 4), ivec2(1, 5),
            ivec2(2, 6), ivec2(3, 7));

const vec3 cubeVertices[8] =
    vec3[](vec3(0.0, 0.0, 0.0), vec3(1.0, 0.0, 0.0), vec3(1.0, 1.0, 0.0),
           vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, 1.0), vec3(1.0, 0.0, 1.0),
           vec3(1.0, 1.0, 1.0), vec3(0.0, 1.0, 1.0));

void main() {
  uint proxyId = gl_GlobalInvocationID.x;

  if (proxyId >= pushConstants.count) {
    return;
  }

  DebugAabb aabb = inDebugAabbs[proxyId];
  vec3 worldCorners[8];

  for (int i = 0; i < 8; ++i) {
    worldCorners[i] = mix(aabb.minExtents, aabb.maxExtents, cubeVertices[i]);
  }

  for (int i = 0; i < 12; ++i) {
    uint vertexIndex = proxyId * 24u + uint(i) * 2u;
    outLineVertices[vertexIndex] = vec4(worldCorners[cubeEdges[i].x], 1.0);
    outLineVertices[vertexIndex + 1u] = vec4(worldCorners[cubeEdges[i].y], 1.0);
  }
}