#version 460 core

// Copyright 2026 m4jr0. All Rights Reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

layout(local_size_x = 256) in;

layout(std140, binding = 50) uniform SparseUploadPushConstants { uint count; }
pushConstants;

layout(std430, binding = 0) readonly buffer InWordIndicesSsbo {
  uint inWordIndices[];
};

layout(std430, binding = 1) readonly buffer InWordsSsbo { uint inWords[]; };

layout(std430, binding = 2) buffer OutWordsSsbo { uint outWords[]; };

void main() {
  uint id = gl_GlobalInvocationID.x;

  if (id >= pushConstants.count) {
    return;
  }

  uint wordIndex = inWordIndices[id];
  outWords[wordIndex] = inWords[id];
}