# Copyright 2026 m4jr0. All Rights Reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

################################################################################
#
# Comet runtime library CMake file
#
################################################################################

add_library(${COMET_RUNTIME_TARGET} STATIC)

comet_configure_target(${COMET_RUNTIME_TARGET})

# Source files #################################################################
set(COMET_RUNTIME_SOURCES
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/runtime_define.h"

  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/animation_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/animation_override.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/animation_pose.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/animation_skinning.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/component/animation_component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/utils/animation_pose_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/animation/utils/animation_skinning_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/camera/camera.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/camera/camera_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/camera/camera_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/conf/conf_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/conf/config_defaults.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/conf/config_keys.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/conf/config_value.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/continuation/continuation_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/continuation/continuation_phase_label.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/continuation/continuation_phase.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/continuation/continuation_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/archetype.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_changes_fence.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_event.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_flush.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_id.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_memory_context.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/entity_type.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/factory/entity_factory_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/factory/handler/entity_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/factory/handler/entity_model_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/factory/handler/entity_primitive_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/label/entity_changes_fence_label.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_data_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_pending_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_read_iteration_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_read_operation_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_reads_during_flush_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/manager_impl/entity_manager_write_operation_template.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/pending_entity.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/utils/archetype_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/entity/utils/entity_id_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/environment/environment_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/event/event_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/event/event.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_allocator.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_container.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_event.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_packet.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/frame/frame_string.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/component/mesh_component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/component/model_component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/component/skeleton_component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/geometry_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/label/mesh_label.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/geometry/mesh.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/input/input_backend.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/input/input_event.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/input/input_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/light/light.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/light/light_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/allocation_tracking.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/allocator/free_list_allocator.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/allocator/platform_allocator.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/allocator/stack_allocator.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/memory_label.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/memory_tag.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/tagged_heap.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/tagged_memory.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/memory/virtual_memory.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/physics/physics_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/profiler/profiler_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/profiler/profiler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/animation/animation_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/animation/animation_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/material/material_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/material/material_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/model/model_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/model/model_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/resource_allocator.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/resource_file_loader.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/resource_handler_utils.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/resource_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/runtime/loaded_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/runtime/resource_slot.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/runtime/resource_slots.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/shader/shader_module_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/shader/shader_module_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/shader/shader_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/shader/shader_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/texture/texture_resource_handle.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/resource/texture/texture_resource_handler.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/scene/scene_event.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/scene/scene_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/shared_instance_registry.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/time/time_manager.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/transform/component/transform_component.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/include/comet/runtime/transform/transform.h"

  "${CMAKE_CURRENT_SOURCE_DIR}/src/animation/animation_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/animation/utils/animation_pose_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/animation/utils/animation_skinning_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/camera/camera_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/camera/camera_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/conf/conf_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/conf/config_defaults.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/continuation/continuation_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/continuation/continuation_phase_label.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/component.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/entity_changes_fence.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/entity_event.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/entity_flush.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/entity_memory_context.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/entity_type.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/factory/entity_factory_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/factory/handler/entity_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/factory/handler/entity_model_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/factory/handler/entity_primitive_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/label/entity_changes_fence_label.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_flush.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_lifecycle.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_pending.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_read_operation.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_reads_during_flush.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/manager_impl/entity_manager_write_operation.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/utils/archetype_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/entity/utils/entity_id_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/environment/environment_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/event/event_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/event/event.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/frame/frame_allocator.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/frame/frame_event.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/frame/frame_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/frame/frame_packet.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/geometry/geometry_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/geometry/label/mesh_label.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/input/input_event.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/input/input_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/light/light_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/allocator/free_list_allocator.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/allocator/platform_allocator.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/allocator/stack_allocator.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/allocation_tracking.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/memory_label.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/tagged_heap.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/tagged_memory.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/memory/virtual_memory.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/physics/physics_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/profiler/profiler_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/profiler/profiler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/animation/animation_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/material/material_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/model/model_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/resource_allocator.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/resource_file_loader.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/resource_handler_utils.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/resource_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/shader/shader_module_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/shader/shader_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/resource/texture/texture_resource_handler.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/scene/scene_event.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/scene/scene_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/time/time_manager.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/transform/transform.cc"
)

target_sources(${COMET_RUNTIME_TARGET}
  PRIVATE
    ${COMET_RUNTIME_SOURCES}
)

# Compiling ####################################################################
target_include_directories(${COMET_RUNTIME_TARGET}
  PUBLIC
    "${CMAKE_CURRENT_SOURCE_DIR}/include"
  PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}/src"
)

# Precompiled headers ##########################################################
target_precompile_headers(${COMET_RUNTIME_TARGET}
  PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}/src/comet_runtime_pch.h"
)

# Linking ######################################################################
target_link_libraries(${COMET_RUNTIME_TARGET}
  PUBLIC
    ${COMET_CORE_TARGET}
    ${COMET_DATA_TARGET}
)